//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autentication
    {
        public int IdToken { get; set; }
        public string User { get; set; }
        public string Pass { get; set; }
        public string Token { get; set; }
        public System.DateTime Inssued { get; set; }
        public System.DateTime Deleted { get; set; }
        public string Status { get; set; }
    }
}
