//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binnacle
    {
        public int BinnacleID { get; set; }
        public string Actions { get; set; }
        public string Users { get; set; }
        public string Error { get; set; }
        public string Messages { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
